development:
  secret_key_base: 917a44e52e0844af822a8fc397cd1c28b92a3c1c6582d2598478e3f169b8e06636db43b2f6b3dc08390ff28145ecdb25ed2f8c00aabcbbda68bc3ed6abbe102e
  encryptable_seed: c5e8

test:
  secret_key_base: 1641ec05b8d93beaa1202a815d880a79fe1d5f6807ef63b8005559ad20bb0ce356f65168f60ed6ca2c0fad3c6848f14ecf3a29816346301819de00ba3dd421e6
  encryptable_seed: 890f
